### ISSUE TITLE
Update How You Can Help form

### ISSUE THREAD

**Issue by dianaluepke** [bridgefoundry/bridgefoundry.github.io#104]
Could someone update the link to the How You Can Help form?

The link shows up on the website home page, near the bottom ("Help make stuff happen")

The new link should be this: https://docs.google.com/forms/d/e/1FAIpQLSfnNpjpnVFrUtvM5D-0cZGfqYZFXzv-uyrufDURdiXBtw2foQ/viewform?usp=sf_link
(This version of the form is properly owned by Bridge Foundry and is accessible by the right people.)

Thanks!

**Comment by dianaluepke** [comment]
P.S. Could we also change the text of the link to "Help in other ways" instead of "help make stuff happen"?

**Comment by iisa** [comment]
closed. completed via #110
