### ISSUE TITLE
link to EIN info (via corp docs) - 404

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/bridgefoundry.github.io#158]
I found it linked here: https://bridgefoundry.org/about.html

friend made a donation and said he followed "breadcrumb trail" to find out EIN for corporate match, which led to:
![image](https://user-images.githubusercontent.com/41906/207988605-20732dae-1ac5-4910-abc0-34fa65273505.png)

**Comment by desi** [comment]
fixed by: https://github.com/bridgefoundry/bridgefoundry.github.io/pull/159
