### ISSUE TITLE
How to make a Bridge -- what should link to this?

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/bridgefoundry.github.io#16]
We want a page on the site where this should go.
1. email hello@bridgefoundry.org
2. have a meeting with Sarah Allen (@ultrasaurus) to discuss your understanding of the mission
3. recruit more leaders/teachers!  make sure you have a diverse crew  (we'll help)
4. figure out what to teach
5. hold a workshop
6. repeat

common patterns that work
- organizing with github issues for workshops
- bridgetroll for registration
- work within an existing ecosystem (meetups, connecting with other community organizations, conferences, etc.)

**Comment by ultrasaurus** [comment]
I put a draft outline on this hidden page:  http://bridgefoundry.org/doc/bridge-building.html

Needs more narrative and links!

**Comment by missherico** [comment]
link to railsbridge workshop cookbook 
https://github.com/railsbridge/docs/wiki/Cookbook

boston cookbook
https://github.com/railsbridge-boston/cookbook

**Comment by ultrasaurus** [comment]
link to Bridge Foundry cookbook:  https://github.com/bridgefoundry/WorkshopCookbook/wiki

**Comment by ultrasaurus** [comment]
I think this page is complete -- it just needs to be linked somehow:  http://bridgefoundry.org/doc/bridge-building.html

**Comment by ultrasaurus** [comment]
this is done!
