### ISSUE TITLE
how to make a blog post

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/bridgefoundry.github.io#21]
It would be great to have a web page on the Bridge Foundry site that explains how to make a blog post.  Something like:
1. add a file to _posts with date-name formatted file name
2. add yml "front matter"  (4 lines of text at the top)
3. make a pull request

First version of the doc could be either command line OR via Github user interface, eventually it would be great to have both.

I think it would make sense to link to the doc from the [blog index](http://bridgefoundry.org/blog.html) but am open to any suggestion for where this page should go.

**Comment by crkoehnen** [comment]
I'll take a crack.  I owe you a blog post anyway and need to figure it out myself.

**Comment by ultrasaurus** [comment]
we have a potential volunteer blogger -- @crkoehnen feel like writing "how to make a blog post" ?

**Comment by ultrasaurus** [comment]
this is now in the README
