### ISSUE TITLE
About > What We Do

### ISSUE THREAD

**Issue by missherico** [bridgefoundry/bridgefoundry.github.io#32]
Goal: 
- [ ] create a page with the following content below.
- [ ] Make a top link area that connects to the sectioned content

content:
--------------
--------------

### Viral Workshop Model
The effect on the local SF Ruby Meetup was just one example of the impact of the RailsBridge workshops.  Every year, multiple new organizations have started, explicitly borrowing the format, processes, and inspiration, which we call the “viral workshop model.”

1. After creating an open source curriculum and putting on a first event, the rest of the work is match-making existing volunteers and resources.
2. Tapping into the people and the companies in the community, an ongoing sustainable teaching community can be created.
3. Students become TAs become Teachers.  The best teachers are those who have learned most recently, and have a passion for giving back to a community that fostered their own development.
4. Companies benefit when we expand the talent pool, and their staff who volunteer at workshops become more expert through teaching and improving their leadership and communication skills.

### Patterns for levelling up
We have many experienced developers who hone their skills through teaching, learning a new language or framework, or contributing to one of our open source projects.  For people who are new to coding and want to become software developers, we have few resources after the intro workshops.  We believe that we can extend our current model to support someone throughout their journey from novice to expert developer.  We already have many success stories of women who came to RailsBridge to learn to code and are now working in the field; however, we still hear of people who aren’t sure what to do after their first or second workshop.  

The transition from student to teaching assistant to teacher is one effective path, but it is not sufficient.  We have experimented with pair programming evenings, mob programming, study groups, co-working days at Internet Cafés and post-workshop hack nights.  These are all good and can be effective, but we aspire to create a path (which may be non-linear) that people could follow to become a practicing software developer.

### Outreach
We believe that if more people know what we were doing, that can create as much positive change as teaching coding and leadership.  There are many great untold stories of learning, teaching and transformational change -- with new stories created every month.  We would like to do more outreach to participants to invite and support them in telling their stories.  

We embrace diversity in style -- with a delightful variety of logos and imagery across our many constituent groups.  We believe we can create some unifying messaging and branding that could connect our ecosystem of communities.  We would like to provide simple common element (widget or footer), which all the groups could embed on their sites.  There is also plenty of room to improve the web and social media presence of Bridge Foundry, which could set patterns for the Bridges.

If you want to help in any way, let us know (link to hello@bridgefoundry.org).

**Comment by audiodude** [comment]
Was working on this just now, but I'm not sure if you mean that you want a separate page like this:

https://www.dropbox.com/s/b0jj7biucjvdcek/Screenshot%202016-01-10%2019.56.26.png?dl=0

Or if you want this to be somehow part of the About page. If the latter is the case, what does the "top link area" look like? Is it just a table of contents?

**Comment by iisa** [comment]
Hi @audiodude yes let's nest it under the About section in the nav.

Yes to the table of contents on the top of the What We Do page.  Can just be flush to the right margin, or an unordered list that links to their relative anchor tags.

**Comment by audiodude** [comment]
> let's nest it under the About section in the nav.

The current nav is just a flat list of links. Do you mean that you'd like to turn it into some kind of nav menu? If that's the case, I assume that "Home" and "Blog" remain flat items and just "About" is a menu?

**Comment by iisa** [comment]
@audiodude nesting in the nav would be ideal

if the page is ready, you can PR the page and we'll make another issue for updating the nav to be nested. =)

**Comment by audiodude** [comment]
The What We Do page is largely done, except that it doesn't have a "table of contents".

**Comment by missherico** [comment]
sweeeeet. looking forward to it

**Comment by audiodude** [comment]
Here is a screenshot of the page:

https://www.dropbox.com/s/akhhxy47lolv99o/Screenshot%202016-01-11%2014.52.57.png?dl=0

**Comment by missherico** [comment]
looks good to PR.
I will add an issue re: nested Nav for What We Do section...

**Comment by audiodude** [comment]
PR is linked above: #36
