### ISSUE TITLE
GitHub Pages was recently upgraded to Jekyll 3.0, we need to do some stuff

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/bridgefoundry.github.io#40]
You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by audiodude** [comment]
It looks like the primary functionality that you were using from rdiscount was the "smartypants" extension "smart".

```
rdiscount:
  extensions: [smart]
```

From what I can tell, this is a stylistic modification that changes smart quotes, such as get munged by Microsoft Word, into regular quotes so they don't look mangled like so:

```
Weâ€™re bridge builders
```

And in fact, the latter is what I see when I change the markdown to use kramdown.

**Comment by audiodude** [comment]
It looks like the "smartypants" substitutions are automatically done in kramdown:

https://github.com/gettalong/kramdown/issues/235

So all I had to do to fix the mangled smart quotes was add a `<meta name="charset" content="utf-8">` tag to the top of the page.

**Comment by ultrasaurus** [comment]
resolved.  thanks!
