### ISSUE TITLE
refactor to use jekyll to remove duplicate code for header and footer 

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/bridgefoundry.github.io#5]
I like the simplicity of using github pages, since I want to keep this to a content-only website for now.  I think [Jekyll](http://jekyllrb.com/) is a nice solution for generating pages with some common elements.  

It would be delightful if someone wanted to refactor the site to use jekyll for it's two current pages, then we can grow it into a bigger site without a lot of repeated code.

**Comment by Vibhuti** [comment]
done! https://github.com/bridgefoundry/bridgefoundry.github.io/pull/9

**Comment by ultrasaurus** [comment]
fixed in branch:  https://github.com/bridgefoundry/bridgefoundry.github.io/tree/blog
