### ISSUE TITLE
How is code-of-conduct implemented?

### ISSUE THREAD

**Issue by audiodude** [bridgefoundry/bridgefoundry.github.io#55]
Very curious. I don't see any page with that title in the jekyll source code. It's not available on local builds (you get a 404 not found).

curl'ing the URL says that the response comes from `Server: GitHub.com`

What sorcery is this?

**Comment by ultrasaurus** [comment]
It lives in a separate repo:  https://github.com/bridgefoundry/code-of-conduct

it gets mapped into a path on the bridgefoundry domain through the magic of github pages
