### ISSUE TITLE
Merge or drop posts from WordPress site?

### ISSUE THREAD

**Issue by maiki** [bridgefoundry/bridgefoundry.github.io#68]
Hiya folks! I am doing some (late) spring cleaning, and realized I have a blog that is still live, but hasn't been updated since 2014. It lives at http://blog.bridgefoundry.org/.

I am not entirely sure, but I suspect the current site is a static generator, so if you let me know which one, I can do an export of the blog posts and drop them in a pull request.

That is, of course, if you folks want to keep them at all. Let me know!

Calling attention to @ultrasaurus, as e was my primary liaison for hosting. ^_^

**Comment by ultrasaurus** [comment]
@maiki I think all of those got migrated here:  https://blog.railsbridge.org/

@rachelmyers @lilliealbert -- can you confirm?

**Comment by maiki** [comment]
Oh! I had no idea. I just spot checked for a handful of months and the posts are living on the new site. Excellent, thanks! =]
