### ISSUE TITLE
Add a Flipcause Donation test page to The Bridge Foundry site

### ISSUE THREAD

**Issue by mfjenn** [bridgefoundry/bridgefoundry.github.io#71]
We need to request an integration using the form below, come up with email text, and integrate it into our website "bridgefoundry.org/donate"

- [X] Submit integration request form: 
https://docs.google.com/forms/d/e/1FAIpQLScgvgqrVn1WjquS1XDYGRWdVA2yVXCkbr7O8zOFczYhA1rUSw/viewform?c=0&w=1
- [x] Make a page on bridgefoundry.org site that isn't linked from anywhere
- [x] Sarah will make a donation to test it
- [x] provided that works, send a test tweet and see how it goes
- [x] if all goes well, add to Bridge Foundry navigation and/or homepage

**Comment by ultrasaurus** [comment]
I'll take a look at doing this today

**Comment by ultrasaurus** [comment]
I submitted the form with this text: https://docs.google.com/document/d/1J5W7RIC7JksDlplJHuchrd7BFc0zrUSiil1jPpUHidY/edit#heading=h.d12r4ky374dx

many thanks to @jasonshen who helped me draft text for social media shoutouts

**Comment by ultrasaurus** [comment]
I made a page, which works as far as accepting a donation, but the email receipt subject line wasn't customizable.  I have a call into support.  They said they will roll out a fix in about a week.

**Comment by ultrasaurus** [comment]
added link to home page (removed paypal button)
