### ISSUE TITLE
Code of Conduct Missing

### ISSUE THREAD

**Issue by thejessleigh** [bridgefoundry/bridgefoundry.github.io#75]
It looks like your CoC page is missing. I use this as an example of a great lightweight code of conduct for small communities and would like to be able to access it again.

https://bridgefoundry.org/code-of-conduct/ leads to a 404 and I'm not finding any file in this repo that it would be pointing to. If BF no longer supports this code of conduct, could you make the original text available in a gist? Thanks.

**Comment by mfjenn** [comment]
Hi Jess, I'll find it for you. Thanks for the heads up about this.

**Comment by ultrasaurus** [comment]
FYI: it's in a separate repo -- got unlinked when we moved from github pages to https.  Should be fixed now.
