### ISSUE TITLE
Homepage: "Workshops" should be "Bridges"

### ISSUE THREAD

**Issue by mfjenn** [bridgefoundry/bridgefoundry.github.io#77]
https://bridgefoundry.org/ Technically the list under the header "Workshops" is of Bridges. Shouldn't the header reflect that? 

I understand that "Workshops" may be more useful to the initial visitor, but it might be easier in the long run if we just call the bridges "Bridges" right off the bat.

**Comment by ultrasaurus** [comment]
We changed these to "Volunteer communities" at some point over the summer to clarify that these were volunteer-led initiatives.

**Comment by ultrasaurus** [comment]
closing since I think this isn't needed anymore...  re-open with a comment if you think something still should be changed here
