### ISSUE TITLE
Get main site Jekyll version up to the same version as sub-repos

### ISSUE THREAD

**Issue by audiodude** [bridgefoundry/bridgefoundry.github.io#89]
Thoughts? This will make it faster/easier to checkout the site and build it for the first time.

**Comment by ultrasaurus** [comment]
huh?  not sure what this means...

**Comment by ultrasaurus** [comment]
I just realized what you meant -- we have two submodules:
* https://github.com/bridgefoundry/code-of-conduct
* https://github.com/bridgefoundry/workshop-map

I just updated the gems in this repo, so would be a good time to update the others too!

**Comment by mxie** [comment]
All gems have been updated in these repos today. Closing! :)
